name: paginate
description: Customizable scroll pagination which lazily adds data as the user scrolls down the screen
version: 0.0.1
repository: https://github.com/predatorx7/paginate

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
